name: Create Daily Discussion

on:
  schedule:
    # 매일 KST 08:00 (UTC 23:00 전날)
    - cron: '0 23 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  create-discussion:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    
    steps:
      - name: Get current date (KST)
        id: date
        run: |
          # UTC+9 적용하여 한국 날짜 계산
          DATE=$(TZ=Asia/Seoul date +'%Y-%m-%d')
          echo "date=$DATE" >> $GITHUB_OUTPUT
      
      - name: Create Discussion
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api graphql -f query='
            mutation($repositoryId: ID!, $categoryId: ID!, $title: String!, $body: String!) {
              createDiscussion(input: {
                repositoryId: $repositoryId
                categoryId: $categoryId
                title: $title
                body: $body
              }) {
                discussion {
                  id
                  number
                  url
                }
              }
            }
          ' \
          -f repositoryId="${{ github.event.repository.node_id }}" \
          -f categoryId="YOUR_GENERAL_CATEGORY_ID" \
          -f title="${{ steps.date.outputs.date }} - 데일리스크럼" \
          -f body=""